version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: unva23azu38
  web: 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create &&
                      rails s -p 3000 -b '0.0.0.0'"
                      # rails db:create && rails db:migrate RAILS_ENV=development
    volumes:
      - .:/task_manager
    ports:
      - "3000:3000"
    depends_on:
      - db
